const destinations = [
  {
    id: 1,
    name: "Santorini Grand Hotel",
    location: "Santorini, Greece",
    region: "europe",
    price: 289,
    priceRange: "luxury",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=600&fit=crop",
    badge: "Featured",
    description: "Experience breathtaking sunsets from your private balcony overlooking the iconic blue-domed churches and crystal-clear Aegean waters.",
    amenities: ["Ocean View", "Infinity Pool", "Spa", "Fine Dining"],
    reviews: 1247
  },
  {
    id: 2,
    name: "Kyoto Traditional Ryokan",
    location: "Kyoto, Japan",
    region: "asia",
    price: 195,
    priceRange: "moderate",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&h=600&fit=crop",
    badge: "Authentic",
    description: "Immerse yourself in Japanese culture with traditional tatami rooms, kaiseki cuisine, and tranquil zen gardens.",
    amenities: ["Hot Spring", "Traditional Cuisine", "Garden", "Tea Ceremony"],
    reviews: 892
  },
  {
    id: 3,
    name: "Banff Mountain Lodge",
    location: "Banff, Canada",
    region: "americas",
    price: 245,
    priceRange: "moderate",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=600&fit=crop",
    badge: "Adventure",
    description: "Nestled in the heart of the Canadian Rockies, offering unparalleled access to hiking, skiing, and pristine mountain lakes.",
    amenities: ["Mountain View", "Ski Access", "Fireplace", "Wildlife Tours"],
    reviews: 1056
  },
  {
    id: 4,
    name: "Bali Beachfront Villa",
    location: "Ubud, Bali",
    region: "asia",
    price: 175,
    priceRange: "moderate",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop",
    badge: "Top Rated",
    description: "Private villa surrounded by lush rice terraces, featuring an infinity pool and traditional Balinese architecture.",
    amenities: ["Private Pool", "Yoga Studio", "Spa", "Organic Dining"],
    reviews: 1523
  },
  {
    id: 5,
    name: "Parisian Boutique Hotel",
    location: "Paris, France",
    region: "europe",
    price: 320,
    priceRange: "luxury",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1549294413-26f195200c16?w=800&h=600&fit=crop",
    badge: "Luxury",
    description: "Elegant accommodations in the heart of Le Marais, walking distance to the Louvre and Notre-Dame Cathedral.",
    amenities: ["City Center", "Rooftop Bar", "Concierge", "Michelin Restaurant"],
    reviews: 978
  },
  {
    id: 6,
    name: "Iceland Northern Lights Resort",
    location: "Reykjavik, Iceland",
    region: "europe",
    price: 280,
    priceRange: "luxury",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1483653364400-eedcfb9f1f88?w=800&h=600&fit=crop",
    badge: "Unique",
    description: "Glass igloos and private hot tubs designed for optimal Aurora Borealis viewing in complete comfort.",
    amenities: ["Northern Lights", "Hot Tub", "Guided Tours", "Geothermal Spa"],
    reviews: 734
  },
  {
    id: 7,
    name: "Sydney Harbour Hotel",
    location: "Sydney, Australia",
    region: "oceania",
    price: 265,
    priceRange: "luxury",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop",
    badge: "Waterfront",
    description: "Stunning harbor views with direct sightlines to the Opera House and Harbour Bridge from premium suites.",
    amenities: ["Harbor View", "Rooftop Pool", "Fine Dining", "Business Center"],
    reviews: 1134
  },
  {
    id: 8,
    name: "Marrakech Riad Retreat",
    location: "Marrakech, Morocco",
    region: "europe",
    price: 125,
    priceRange: "budget",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&h=600&fit=crop",
    badge: "Cultural",
    description: "Traditional Moroccan riad with intricate tilework, peaceful courtyard fountain, and rooftop terrace overlooking the medina.",
    amenities: ["Rooftop Terrace", "Traditional Hammam", "Courtyard", "Local Cuisine"],
    reviews: 645
  },
  {
    id: 9,
    name: "New York Urban Loft",
    location: "Manhattan, USA",
    region: "americas",
    price: 295,
    priceRange: "luxury",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=600&fit=crop",
    badge: "Modern",
    description: "Sleek contemporary design in a converted warehouse, steps from Times Square and Broadway theaters.",
    amenities: ["City Views", "Fitness Center", "24/7 Concierge", "Smart Rooms"],
    reviews: 1891
  },
  {
    id: 10,
    name: "Swiss Alpine Chalet",
    location: "Zermatt, Switzerland",
    region: "europe",
    price: 340,
    priceRange: "luxury",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    badge: "Premium",
    description: "Luxury chalet with direct views of the Matterhorn, featuring a private sauna and ski-in/ski-out access.",
    amenities: ["Matterhorn View", "Private Sauna", "Ski-in/Ski-out", "Gourmet Kitchen"],
    reviews: 567
  },
  {
    id: 11,
    name: "Tuscany Vineyard Estate",
    location: "Florence, Italy",
    region: "europe",
    price: 210,
    priceRange: "moderate",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&h=600&fit=crop",
    badge: "Romantic",
    description: "Historic villa surrounded by vineyards and olive groves, offering wine tastings and cooking classes.",
    amenities: ["Wine Tasting", "Cooking Classes", "Pool", "Vineyard Tours"],
    reviews: 823
  },
  {
    id: 12,
    name: "Dubai Desert Resort",
    location: "Dubai, UAE",
    region: "asia",
    price: 380,
    priceRange: "luxury",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
    badge: "Exclusive",
    description: "Ultra-luxury desert oasis with private pools, camel rides, and world-class dining under the stars.",
    amenities: ["Private Pool", "Desert Safari", "Fine Dining", "Spa"],
    reviews: 1092
  }
];
